name: Test

on:
  pull_request:
  push:
    branches: [main, issue-*]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test-unit

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up git committer identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test-e2e

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up git committer identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install dependencies and build
        run: yarn install && yarn build && yarn package

      - name: Create a temp git dir
        run: |
          mkdir ${{ runner.temp }}/temp_git_dir
          cd ${{ runner.temp }}/temp_git_dir
          git config --global init.defaultBranch main
          git init
          git status

      - name: Create new job
        id: create-job
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'create-job'
          job_payload: '{"field": "value", "state": "pending"}'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Mark job as started
        id: start-job
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'start-job'
          job_id: '1'
          job_payload: '{"field": "value", "state": "started"}'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Mutual exclusion code
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        run: echo "Running the job that requires mutual exclusion"

      - name: Get next job
        id: get-next-job
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'next-job'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Mark job as finished
        id: finish-job
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'finish-job'
          job_id: '1'
          job_payload: '{"field": "value", "state": "finished"}'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Show new commits
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git show --pretty="fuller" --show-signature ${{ steps.create-job.outputs.job_commit }}
          git show --pretty="fuller" --show-signature ${{ steps.start-job.outputs.job_commit }}
          git show --pretty="fuller" --show-signature ${{ steps.finish-job.outputs.job_commit }}

      - name: Upload test git dir
        uses: actions/upload-artifact@v3
        with:
          name: Integration test git dir
          path: ${{ runner.temp }}/temp_git_dir

  integration-tests-with-commit-signature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git config
        run: |
          # Import test GPG key
          # secretlint-disable
          {
            echo -e "-----BEGIN PGP PRIVATE KEY BLOCK-----\n"
            cat __tests__/fixtures/test-key-committer.pgp
            echo -e "\n-----END PGP PRIVATE KEY BLOCK-----\n"
          } | gpg --import --batch --yes -
          # secretlint-enable
          # Set Git config
          git config --global user.name 'A Committer'
          git config --global user.email 'committer@example.com'
          git config --global user.signingkey 'BD98B3F42545FF93EFF55F7F3F39AA1432CA6AD7'
          git config --global commit.gpgsign true

      - name: Install dependencies and build
        run: yarn install && yarn build && yarn package

      - name: Create a temp git dir
        run: |
          mkdir ${{ runner.temp }}/temp_git_dir
          cd ${{ runner.temp }}/temp_git_dir
          git config --global init.defaultBranch main
          git init
          git status

      - name: Create new job
        id: create-job
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'create-job'
          job_payload: '{"field": "value", "state": "pending"}'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Mark job as started
        id: start-job
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'start-job'
          job_id: '1'
          job_payload: '{"field": "value", "state": "started"}'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Mutual exclusion code
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        run: echo "Running the job that requires mutual exclusion"

      - name: Get next job
        id: get-next-job
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'next-job'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Mark job as finished
        id: finish-job
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./
        with:
          git_repo_dir: ${{ runner.temp }}/temp_git_dir
          queue_name: 'library update - library-aaa'
          action: 'finish-job'
          job_id: '1'
          job_payload: '{"field": "value", "state": "finished"}'

      - name: Debug
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git log --show-signature

      - name: Show new commits
        run: |
          cd ${{ runner.temp }}/temp_git_dir
          git show --pretty="fuller" --show-signature ${{ steps.create-job.outputs.job_commit }}
          git show --pretty="fuller" --show-signature ${{ steps.start-job.outputs.job_commit }}
          git show --pretty="fuller" --show-signature ${{ steps.finish-job.outputs.job_commit }}

      - name: Upload test git dir
        uses: actions/upload-artifact@v3
        with:
          name: Integration test git dir
          path: ${{ runner.temp }}/temp_git_dir
